//
//  ContactsStyleKit.m
//  Contacts
//
//  Created by Ilter Cengiz on 27/12/2015.
//  Copyright (c) 2015 Ilter Cengiz. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "ContactsStyleKit.h"


@implementation ContactsStyleKit

#pragma mark Cache

static UIColor* _contactsRedColor = nil;
static UIColor* _contactsWhiteColor = nil;

static UIImage* _imageOfNavigationBarBackground = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _contactsRedColor = [UIColor colorWithRed: 0.851 green: 0.05 blue: 0.05 alpha: 1];
    _contactsWhiteColor = [UIColor colorWithRed: 0.971 green: 0.971 blue: 0.971 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)contactsRedColor { return _contactsRedColor; }
+ (UIColor*)contactsWhiteColor { return _contactsWhiteColor; }

#pragma mark Drawing Methods

+ (void)drawNavigationBarBackground
{

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 320, 64)];
    [ContactsStyleKit.contactsRedColor setFill];
    [rectanglePath fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfNavigationBarBackground
{
    if (_imageOfNavigationBarBackground)
        return _imageOfNavigationBarBackground;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(320, 64), NO, 0.0f);
    [ContactsStyleKit drawNavigationBarBackground];

    _imageOfNavigationBarBackground = [UIGraphicsGetImageFromCurrentImageContext() resizableImageWithCapInsets: UIEdgeInsetsZero resizingMode: UIImageResizingModeTile];
    UIGraphicsEndImageContext();

    return _imageOfNavigationBarBackground;
}

#pragma mark Customization Infrastructure

- (void)setNavigationBarBackgroundTargets: (NSArray*)navigationBarBackgroundTargets
{
    _navigationBarBackgroundTargets = navigationBarBackgroundTargets;

    for (id target in self.navigationBarBackgroundTargets)
        [target performSelector: @selector(setImage:) withObject: ContactsStyleKit.imageOfNavigationBarBackground];
}


@end
