//
//  ContactsStyleKit.h
//  Contacts
//
//  Created by Ilter Cengiz on 27/12/2015.
//  Copyright (c) 2015 Ilter Cengiz. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ContactsStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* navigationBarBackgroundTargets;

// Colors
+ (UIColor*)contactsRedColor;
+ (UIColor*)contactsWhiteColor;

// Generated Images
+ (UIImage*)imageOfNavigationBarBackground;

@end
